### ISSUE TITLE
Windows Phone 8.1

### ISSUE THREAD

**Issue by kmmartins** [serbanghita/Mobile-Detect#226]
I would like support for wp 8.1
I've added it:
'WindowsPhoneOS'   => 'Windows Phone 8.0|Windows Phone OS|XBLWP7|ZuneWP7|Windows Phone 8.1'

**Comment by robertfausk** [comment]
Will there be any progress on this issue?

**Comment by FredyWenger** [comment]
Thanks to MS for this meaningful string!
=> In our portal, I query the string and then show a special mobile page for iOS, Android and Windows Phone.
Of cause the "meaningful" string the portal has showed the iOS page instead of the WP page (iPhone in the string).
To don't make it too easy, the "meaningful" user agent string is only submitted, if the mobile IE is set to "Mobile" and the portal is called over the Internet. If the mobile IE is set to "Desktop" or the portal is called over the LAN - why ever - another string is submitted.
This has cost me over a full day to find the problem and a workaround.
The workaround is, to query the uas first for "Windows Phone" (before query for iPhone).
