### ISSUE TITLE
A function to add an identifier for mobile_detect

### ISSUE THREAD

**Issue by ClementDerouet** [serbanghita/Mobile-Detect#274]
As mobile_detect can not support every device, it must allow to add new detection function from a method of the mobile_detect class. So, we have not to have a second API to detect some devices that exist not in your library.

**Comment by nicktacular** [comment]
In the upcoming 3.0 release, the issue is that there's more to detection than a regex match. If you look at an [iPhone example](https://github.com/serbanghita/Mobile-Detect/blob/devel-3/lib/Providers/Phones.php#L13) there's the part of matching followed by extracting the device attributes from the User-Agent header.

I believe the better approach here is to create a PR to add support for a device that exists out there.

The second option, if we wish to expand this functionality, is to create a class / interface that would represent a match set. For example:

```php
$matchSet = new MatchSet();
$matchSet->setRegex('Android');
$matchSet->addNamedMatch('Version: (?<version>[a-z0-9]+)');
$matchSet->addNamedMatch('Whatever (?<whatever>.{1,3})');
$matchSet->setVendor('Google');
$matchSet->setIsMobile(true);

$mobileDetect = new MobileDetect(/* some args */, [$matchSet]);

$mobileDetect->detect()->isMobile(); //true
```

My only thought here is I'm not sure this is requested sufficiently to open up an API for this, versus just adding new devices by a PR. Thoughts?

**Comment by clement961** [comment]
I'm proposed this idea because some devices like smart TVs are not detectable with the current version. I agree, this functionality is not requested sufficiently to create an API. But it needs nevertheless to add this functionality, because we cannot support all devices that exists. So it is best to choose an easy option than nothing.

**Comment by nicktacular** [comment]
Ok @clement961 we will add this to the 3.1 milestone since we need to discuss the best way to accomplish this,

**Comment by clement961** [comment]
I think the best way is a method like this for the Mobile_Detect class : 

public void add_match_set ( string $key, string $regex[, array $named_match[, array $option]] )

$key : the key to use as argument in the Mobile_Detect::is() method. 
$regex : the pattern to parse the user agent. 
$named_match : an optional array to add the named matches. 
$option : an optional array to specify other informations about the device, like for example, the vendor or if it is a mobile.
