### ISSUE TITLE
All BrowserStack Android tablets are detected as phone

### ISSUE THREAD

**Issue by samdark** [serbanghita/Mobile-Detect#35]
- Amazon Kindle Fire 2
- Amazon Kindle Fire HD 8.9
- Google Nexus 7
- Samsung Galaxy Note 10.1
- Samsung Galaxy Tab 2 10.1

I've verified with real Galaxy Note 10.1 and it's detected as phone as well. UA string is

```
Mozilla/5.0 (Linux;U Android 4.04; nl-nl; GT-N8010 Build/IMM76D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30
```

**Comment by dani3l** [comment]
Happened to me too now. I wanted to send different output based on device category, but if I acciddently send phone html to a tablet that won't be good :X 

I checked the useragents of galaxy tabs / notes and in mobile detect it actually detects as tablet but I'm not sure if this is browserstack issue or because using chrome/stock browser differences.

Anyone have any idea how to confirm that?
