### ISSUE TITLE
Chrome update makes detect desktop navigation as mobile

### ISSUE THREAD

**Issue by arqueido** [serbanghita/Mobile-Detect#363]
Hello,

it seems that Mobile-Detect has a problem with the last update of Chrome for desktop 41.0.2272.89 and it detect it as mobile navigator.

Thanks

**Comment by arqueido** [comment]
The problem is related with the LG model 272 that match with the number version of the new update of  Chrome.

**Comment by patrickq** [comment]
@arqueido I noticed this recently as well.  You are likely using an older copy of the library, as I was.  If you pull the latest version, you should notice that the issue goes away.  The specific change that appears to fix the problem is this one https://github.com/serbanghita/Mobile-Detect/commit/fdd6f8bebf54a09f152b51d5fa5699456d4f35e7#diff-77cafe0d78b7a9dc8c9183a06faf8e56

**Comment by serbanghita** [comment]
@patrickq thanks for the assist :+1:
