### ISSUE TITLE
Issues when no User Agent string is available

### ISSUE THREAD

**Issue by davidfarina** [serbanghita/Mobile-Detect#420]
I am having the problem that when I am using Google Chrome 43.0.2357.124 m it does not give a User Agent string. $detect->isMobile() fails silently and I am not getting it to work. Any help?

I already tried:

require_once( 'Mobile_Detect.php' );
  $detect = new Mobile_Detect;
  $isMobile = false;
  
  if ($detect->isMobile()) {
	$isMobile = true;
  }
  
  print_r($isMobile);

The print_r prints nothing, but printing $detect only it correctly displays the Mobile_Detect object...

**Comment by serbanghita** [comment]
@davidfarina Hi! First of all `Mobile_Detect` fallsback to `$_SERVER` array if no headers of User-Agent is given (see line 675), this is expected behavior.

Use it like this `$isMobile = $detect->isMobile();` in your case `$isMobile` will be `FALSE`.
To get the User-Agent use `$detect->getUserAgent()`

**Comment by davidfarina** [comment]
I really dont get it whats happening. Now i have it like that:

<?php
  error_reporting(E_ALL);
  require_once( 'Mobile_Detect.php' );
  $detect = new Mobile_Detect;
  
  $isMobile = $detect->isMobile();
  
  print_r($isMobile);
  ?>

It prints nothing?

**Comment by nicktacular** [comment]
Casting a boolean to a string means it'll be empty:
```
php > $a = false;
php > print_r($a);
php > 
```

Try a var_dump on `$isMobile` and you'll see it's boolean `false`.
