### ISSUE TITLE
Zend error 

### ISSUE THREAD

**Issue by libertamohamed** [serbanghita/Mobile-Detect#439]
I am receiving "Internal Zend error - Missing class information on line 29" i think APC is causing this. Is there any solution beside disabling APC?

**Comment by nicktacular** [comment]
Based on what I've been able to research, this is likely an issue with attempting to load the class dynamically multiple times rather than an APC issue. You will need to provide a lot of details here regarding php version, modules, and how you are including the actual class in your code. Are you using composer to autoload? Are you building your own autoloader? Are you using multiple autoloaders?

**Comment by serbanghita** [comment]
No additional info given, will close temporarly.
