### ISSUE TITLE
Please, make an exception with the Pale Moon web browser

### ISSUE THREAD

**Issue by KNTRO** [serbanghita/Mobile-Detect#500]
Please specify the User-Agent. Go to http://is.gd/mobiletest and copy-paste it here.

Hi there. Please, make an exception with the Pale Moon web browser's user agent strings:

**Pale Moon 26 x64 on Windows 10 64 bits**:
* _Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:38.9) Gecko/20100101 Goanna/2.0 Firefox/38.9 PaleMoon/26.0.0_
* _Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:2.0) Gecko/20100101 Goanna/20160121 PaleMoon/26.0.0_

Note, these strings include _Goanna_ [not _GOA_!], which is the Pale Moon's render engine.

Pale Moon is a desktop/laptop web browser for GNU/Linux & Windows.

More info about this, [here](https://forum.palemoon.org/viewtopic.php?f=37&t=10856#p76170).

Thank yo so much in advance! :ok_woman:

**Comment by wolfbeast** [comment]
@KNTRO Thanks for opening this issue and providing a description.
For general information about the structure of our useragent, please see [this post](https://forum.palemoon.org/viewtopic.php?f=24&t=9077) on the forum.

We're running into some annoying and very inconvenient web compatibility issues with our users because a good number of sites and web apps (including some popular ones like inoreader) use your detection library and currently forward all desktop/laptop users to mobile versions of sites without option. it's unfortunate that your library only seems to do a partial match on "goa" and catching our browser in the current.

Hoping you'll make this a quick change&improvement, and thanks in advance.

**Comment by Nindaleth** [comment]
:+1:

**Comment by ThaDafinser** [comment]
@KNTRO so the tests from `WhichBrowser` are valid? There is no mobile version?
https://github.com/WhichBrowser/Parser/blob/910b7f5dec3633f373cb029747c6334786a418f9/tests/data/desktop/engine-goanna.yaml

**Comment by wolfbeast** [comment]
@ThaDafinser Correct, there is currently no mobile version of Pale Moon with the Goanna engine. Depending on how well it can be ported to Android, there may never be, but that's something to find out later.

**Comment by TPS** [comment]
#528, if merged, apparently solves this.

**Comment by wolfbeast** [comment]
Please push any fix to a release version sometime soon. We keep running into this issue and your script is fairly widely used, also by high-profile sites.

**Comment by TPS** [comment]
#528 is merged, so, pending external/live testing, this likely can be closed. ☺

**Comment by serbanghita** [comment]
Thanks you guys! I cannot thank you enough for your patience. Now I have the PaleMoon User-agents in the tests so there should be no more future conflicts.
