### ISSUE TITLE
bug in getMobileDetectionRules

### ISSUE THREAD

**Issue by brandondlp** [serbanghita/Mobile-Detect#512]
The function isMobile returns true on tablets. This is because getMobileDetectionRules checks for:
                  self::$phoneDevices
                  self::$tabletDevices,
                  self::$operatingSystems,
                  self::$browsers

IsTablet checks correctly only for tablet devices. But isMobile checks for too many devices and systems.

**Comment by ThaDafinser** [comment]
That is correct.  Check the examples first

http://mobiledetect.net/

```php
// Include and instantiate the class.
require_once 'Mobile_Detect.php';
$detect = new Mobile_Detect;
 
// Any mobile device (phones or tablets).
if ( $detect->isMobile() ) {
 
}
 
// Any tablet device.
if( $detect->isTablet() ){
 
}
```

**Comment by microchip8** [comment]
A tablet is also a mobile device

The function isMobile returns true on tablets. This is because
getMobileDetectionRules checks for:
self::$phoneDevices
self::$tabletDevices,
self::$operatingSystems,
self::$browsers

IsTablet checks correctly only for tablet devices. But isMobile checks for
too many devices and systems.

—
Reply to this email directly or view it on GitHub
<https://github.com/serbanghita/Mobile-Detect/issues/512>.

**Comment by brandondlp** [comment]
Ah I missed that. Thanks for pointing that out.
