### ISSUE TITLE
Wrong version "tag" on github Release, 2.2.29 should be 2.8.29

### ISSUE THREAD

**Issue by iroes** [serbanghita/Mobile-Detect#707]
**Issue description**
See the title.

**Comment by serbanghita** [comment]
My bad, in on remote location now, tomorrow i'll fix it. Thank you!

On Dec 16, 2017 12:29, "Isaac Roca Escoda" <notifications@github.com> wrote:

*Issue description*
See the title.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/serbanghita/Mobile-Detect/issues/707>, or mute the
thread

**Comment by serbanghita** [comment]
@iroes thank you for reporting, fixed! 👍
