### ISSUE TITLE
Asus ZenPad 10 Z300C is detected as phone

### ISSUE THREAD

**Issue by officeutils** [serbanghita/Mobile-Detect#727]
Mozilla/5.0 (Linux; Android 5.0.2; P023 Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.109 Safari/537.36

**Comment by ohaag** [comment]
Hello, I've the same problem.

Like said in another ticket, Chrome use "Mobile" in his user-agents according to :
https://developer.chrome.com/multidevice/user-agent

This is a Tablet PC, I don't know how the lib should behave with that kind of device but considering P023 not being in TabletDevices regexes, the "chrome mobile" rule should be applied.

Phone pattern: 'Android' + 'Chrome/[.0-9]* Mobile'
Tablet pattern: 'Android' + 'Chrome/[.0-9]* (?!Mobile)'

P023 is detected as phone only because its UA is in the list of mobile OS and in the list of mobile browsers UA list.

So the second regex should be enough to identity it as a Tablet.
Should a Tablet be considered as a Mobile ? If not, this same regex should moreover be an excluding rule.
