### ISSUE TITLE
Regarding how to generate Mobile_Detect.json

### ISSUE THREAD

**Issue by kongdewen** [serbanghita/Mobile-Detect#737]
**Issue description**
I have several questions regarding Mobile_Detect.json

1, For most of phone brands, it lists specific models for uaMatch, eg. Samsung.  and there are so many models are missing. I won't why it didn't just list `SM-.*Mobile` for general matches based on https://developer.samsung.com/internet/user-agent-string-format.  Is there reason for that? 

2, I can't find vivo, asus, huawei, xiaomi models as well.  I will be glad to help to submit pr these models. Is there any rules on on how generates this json file? and any way I can help?

**Comment by serbanghita** [comment]
@kongdewen 
1. It's because putting a wider regex will potentially generate conflicts. If I would know for sure that only Samsung uses `SM-.*Mobile` than I would probably do it. Another reason is because some of the devices are tablets and need to be specifically extracted from all `SM-*` devices.

2. Look into `Mobile-Detect.php` file. The JSON is generated before release. See https://github.com/serbanghita/Mobile-Detect/blob/master/docs/CONTRIBUTING.md
