### ISSUE TITLE
iPadOS 13 Safari not detected as (is)Tablet or (is)iPad

### ISSUE THREAD

**Issue by AdmDevelopment** [serbanghita/Mobile-Detect#795]
**Issue description**
Using iPadOS 13.0 Beta (1) Safari is sending the User Agent of it's MacOS counterpart. By default Safari will now request the desktop websites on the iPad. Mobiledetect currently thinks the iPad is a Mac using safari.

In slideover mode Safari does request the mobile website and sends the "iPad user agent" with the request. (see screenshot)

**User-Agent(s)**
iPad user agent in iPadOS 13 beta using Safari 13:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15

Would be great if we could somehow detect Safari in normal window mode on the iPad and determine it is a Tablet or iPad.

<img width="1095" alt="screenshot" src="https://user-images.githubusercontent.com/51705707/59274152-0b893f00-8c5a-11e9-826a-980b5f52a4be.png">

**Comment by RyanBlundell** [comment]
My iPad is being detected as a phone

Your UA is Mozilla/5.0 (Linux; Android 7.1.1; SM-P555 Build/NMF26X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Safari/537.36

**Comment by phamhung159** [comment]
you can check this link https://qiita.com/mtdune/items/97abb9c0bd926d4c8a13

**Comment by serbanghita** [comment]
@AdmDevelopment thanks for posting such a detailed report on how `iPadOS` reports the user-agent. I will have to put this into the KNOWN_LIMITATIONS section because there is no way to tell that is a mobile Safari coming from the new Apple device.

@phamhung159 that seems like a client-side technique.

**Comment by Tristanlogd** [comment]
This is actually an option Apple has turned on by default, they are falsely claiming in the user agent that the user is running MacOS  10.15 and an intel chip. You can turn this option off under Settings - Safari - Request Desktop Website on - All Websites

This should not be on by default in my opinion, it’s actually not accurate at all.

**Comment by serbanghita** [comment]
@Tristanlogd thank you for clarifying, I was just reading the conversation at https://github.com/hgoebl/mobile-detect.js/issues/95#issuecomment-534222151 

We're currently stuck with `Intel Mac OS X 10_15` by default apparently.

**Comment by karthejay** [comment]
To switch from desktop to mobile mode in your iPad:

Go to the Settings > Safari > Request Desktop Website.
Under the Request Desktop Website On section, click All Websites to turn off/grey out the toggle.
When the All Websites toggle is greyed out.
Please check after this settings update. you will get the user agent as iPad.

**Comment by zengyuangai** [comment]
'PointerEvent' in window

**Comment by rikinshah23** [comment]
@Tristanlogd @karthejay  what could be solution at this time then? 
I cannot ask user to turn off desktop website option. 
https://stackoverflow.com/questions/58344491/request-browser-ismobiledevice-not-working-with-ipadair2-and-ios-13-0-1

Badly stuck here. need to check IsMobileDevice on server side.

**Comment by emaillenin** [comment]
Apple wants the server to believe the user is using a desktop.

**Comment by OlympicLarry** [comment]
try this

https://stackoverflow.com/questions/58019463/how-to-detect-device-name-in-safari-on-ios-13-while-it-doesnt-show-the-correct

`let isIOS = /iPad|iPhone|iPod/.test(navigator.platform) ||
(navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1)`

**Comment by rhaimann** [comment]
This is messing up a web app I am working on where I want a fixed background for everything EXCEPT iphone and ipads since those devices do not support fixed backgrounds. I've coded sequenced loading of images based on scroll position and load images of varying resolution based on client screen size so as to not overload client memory. I need to modify the style settings for the background for iPhone and iPad in order to stop background image glitching that occurs. Easy enough for iphone and older iPads, but new iPad user-agents replicate Mac user-agents as discussed above.

Closest solution I am coming up with is to write a function to identify if the client is a touch screen or not. Still, macs with touch screens will probably fail that and those clients will wind up scrolling the backgrounds and having background resolution/glitch issues. Unfortunate oversight on the part of Apple, IMHO, unless there is a way to make fixed backgrounds work on the new more powerful iPads someone knows of, hopefully without endless hours of coding animation.

https://stackoverflow.com/questions/56934826/distinguish-between-ipad-and-mac-on-ipad-with-ipados

https://stackoverflow.com/questions/56578799/tell-ipados-from-macos-on-the-web
