### ISSUE TITLE
How to find out what the phone is?

### ISSUE THREAD

**Issue by ErikThiart** [serbanghita/Mobile-Detect#805]
Is there a way to get the phone model?

Like $phone = dedect->phoneModel()

**Comment by devnullzero** [comment]
I'm also looking for this exact feature. I see previous efforts by @StevenMapes around a getDetails() function (issue #15) but it seems to be stalled.

**Comment by ErikThiart** [comment]
Or better yet:

`$phone = detect->getDetails()`

**Comment by serbanghita** [comment]
@ErikThiart @devnullzero yes you are both right, this library needs a `getModel`/`getDetails` but it doesn't have that feature because it was not originally design to do that. I started an initiative on `3.x` branch but I got derailed by personal life. This feature is not and will not be available on the current `2.x`.
