### ISSUE TITLE
3.7.4 Compatibility With PHP 8.0+ 

### ISSUE THREAD

**Issue by semrocc** [serbanghita/Mobile-Detect#961]
As I am not familiar with Composer, and version 4.8 looks overly complicated for myself, a non-programmer, I was wondering if version 3.7.4+ will continue to work with PHP 8.0+

Currently, I have tested version 3.7.4 with PHP 8.3, and there does not appear to be any problems. I would just like to confirm that 3.7.4 will continue to be PHP 8.0+ compatible. Thanks

**Comment by ryanwhowe** [comment]
@semrocc the documentation shows that the `3.74` version is not intended to support PHP 8 (it states <8.0), so you are in a "use at your own risk" situation.  I would consider the `3.74` current `composer.json` file to have a bug in the required php verison setting.  Currently, it shows `>= 7.0` while it should be `^7.0` to exclude support for php 8.  It appears that you are only able to install it in php 8 via composer due to an oversight in the `composer.json` setting.

**Comment by semrocc** [comment]
@ryanwhowe thanks for this information. Currently I only call the MobileDetect.php file and then some variation of:

`if ($detect->isMobile() && !$detect->isTablet())`

Do you expect that the MobileDetect.php file will continue to work with future versions of PHP 8+?

**Comment by ryanwhowe** [comment]
@semrocc looking through the code briefly there are no forward issues that I see with php ^8.0 support.  At its heart, the package is a header parser with an extensive library of mobile and tablet snippets that indicate different types of browsers.  Our usage is similar to yours but we are slowly transitioning to just utilizing css and view ports instead of modifying our backed behavior based on the requester's header browser.

**Comment by semrocc** [comment]
@ryanwhowe thanks for this information, much appreciated.

**Comment by Xon** [comment]
The 3.74.x branch works with php 8.0 to php 8.3, but isn't compatible with php 8.4+ (ref #956). Sadly the PR I had for 3.74.x wasn't accepted

**Comment by semrocc** [comment]
Having the 3.7.4 versions compatible with versions of PHP 8.4+ would certainly be nice for people like myself as Mobile Detect versions 4.8+ will simply not be an option for me.

**Comment by Apollodore** [comment]
@semrocc  version 4.8 is easier now @serbanghita has made a standalone version

**Comment by serbanghita** [comment]
@semrocc I've made it so you can use Mobile Detect with PHP 8.x standalone just a couple of days ago. I've put the steps here: https://docs.mobiledetect.net/home/usage-standalone

@ryanwhowe @Apollodore thank you for the assist 🙏

**Comment by semrocc** [comment]
@serbanghita This sounds great - thanks for your work.

Can you tell me which files/directories are required for the standalone configuration?

**Comment by Apollodore** [comment]
@serbanghita you are welcome, thank you so much for your work.
@semrocc  all files and directories of 4.8.10 version are required (maybe not, I am also a non-programmer, but it works if you keep all the files and directories). As @serbanghita told, he has put the steps here: https://docs.mobiledetect.net/home/usage-standalone
